project:
  type: manuscript
  execute-dir: project

manuscript:
  article: index.qmd

format:
  html: default
  docx: default
  apaish-typst:
    documentmode: doc 
#   documentmode: jou #preprint
#  pdf: default
#  jats: default
format-links:
  - html
  - docx
  - format: apaish-typst
    text: PDF
    icon: file-pdf

execute:
  freeze: auto 



