---
title: "Make 30-fold ROC Figure (Supplement)"
author: "Gaylen Fronk & John Curtin"
date: "`r lubridate::today()`"
number-sections: true
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 4
editor_options: 
  chunk_output_type: console
---

## Set Up Environment

```{r set_values}
version <- "v6"
cv <- "nested"
```

Function conflicts
```{r, packages_workflow}
#| message: false
#| warning: false

# source
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")

# handle conflicts
options(conflicts.policy = "depends.ok")
tidymodels_conflictRules()
```

Packages for script
```{r, packages_script}
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
library(tidyposterior)
library(patchwork)

theme_set(theme_classic()) 
```

Source support functions
```{r source_functions}
# EDA
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")

# CHTC support functions
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/chtc/static_files/fun_chtc.R?raw=true")
```

Absolute paths
```{r, absolute_paths}
switch (Sys.info()[['sysname']],
        # PC paths
        Windows = {
          path_models <- str_c("P:/studydata/match/models/")},
        
        # IOS paths
        Darwin = {
          path_models <- str_c("/Volumes/private/studydata/match/models/")},
        
        # Linux paths
        Linux = {
          path_models <- str_c("~/mnt/private/studydata/match/models/")}
)
```

Chunk Defaults
```{r defaults}
#| include: false

knitr::opts_chunk$set(attr.output='style="max-height: 500px;"')

options(tibble.width = Inf)
options(tibble.print_max = Inf)
```


Source training controls 
```{r source}
# EDA
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")

# ML functions
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")

```

## Read in model performance metrics

```{r read_metrics_preds}

preds4 <- read_rds(file.path(path_models, "pp_hybrid_wk4_outcome",
                             str_c("outer_preds_", version, 
                                   "_", cv, ".rds"))) |> 
  glimpse()

preds12 <- read_rds(file.path(path_models, "pp_hybrid_wk12_outcome",
                             str_c("outer_preds_", version, 
                                   "_", cv, ".rds"))) |> 
  glimpse()

preds26 <- read_rds(file.path(path_models, "pp_hybrid_wk26_outcome",
                             str_c("outer_preds_", version, 
                                   "_", cv, ".rds"))) |> 
  glimpse()

```

## ROC curves

### 4-week model

Set up
```{r}
roc_data4 <- preds4 %>%
  roc_curve(prob_raw, truth = label)

# rocs per fold
roc_folds4 <- preds4 %>%
  nest(.by = outer_split_num, .key = "preds") |> 
  mutate(roc = map(preds, \(preds) roc_curve(preds, prob_raw, 
                                             truth = label)))

fig_roc_folds4 <- roc_data4 %>%  # plot region from full concatenated data 
  ggplot(aes(x = 1 - specificity, y = sensitivity)) + 
  geom_abline(lty = 3) +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(x = "False Positive Rate",
       y = "True Positive Rate") +
  scale_x_continuous(breaks = seq(0,1,.25),
                     labels = sprintf("%.2f", seq(1,0,-.25))) +
  theme(axis.text = element_text(size = rel(0.75)),
        axis.title = element_text(size = rel(1)))

for (i in 1:nrow(roc_folds4)) {
  fig_roc_folds4 <- fig_roc_folds4 +
    geom_path(data = roc_folds4$roc[[i]],
              mapping = aes(x = 1 - specificity, y = sensitivity),
              color = "gray")
}
```

```{r}
#| label: fig-roc-wk4

#add full concatenated curve
fig_roc_all_wk4 <- fig_roc_folds4 +
  geom_path(data = roc_data4,
            mapping = aes(x = 1 - specificity, y = sensitivity, color = "red"),
            linewidth = 2) +
  labs(x = "False Positive Rate",
       title = "Week 4 ROC Curves") +
  theme(legend.position = "none")

fig_roc_all_wk4
```

### 12-week model

Set up
```{r}
roc_data12 <- preds12 %>%
  roc_curve(prob_raw, truth = label)

# rocs per fold
roc_folds12 <- preds12 %>%
  nest(.by = outer_split_num, .key = "preds") |> 
  mutate(roc = map(preds, \(preds) roc_curve(preds, prob_raw, 
                                             truth = label)))

fig_roc_folds12 <- roc_data12 %>%  # plot region from full concatenated data 
  ggplot(aes(x = 1 - specificity, y = sensitivity)) + 
  geom_abline(lty = 3) +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(x = "False Positive Rate",
       y = "True Positive Rate") +
  scale_x_continuous(breaks = seq(0,1,.25),
                     labels = sprintf("%.2f", seq(1,0,-.25))) +
  theme(axis.text = element_text(size = rel(0.75)),
        axis.title = element_text(size = rel(1)))

for (i in 1:nrow(roc_folds12)) {
  fig_roc_folds12 <- fig_roc_folds12 +
    geom_path(data = roc_folds12$roc[[i]],
              mapping = aes(x = 1 - specificity, y = sensitivity),
              color = "gray")
}
```

```{r}
#| label: fig-roc-wk12

#add full concatenated curve
fig_roc_all_wk12 <- fig_roc_folds12 +
  geom_path(data = roc_data12,
            mapping = aes(x = 1 - specificity, y = sensitivity, color = "red"),
            linewidth = 2) +
  labs(x = "False Positive Rate",
       title = "Week 12 ROC Curves") +
  theme(legend.position = "none")

fig_roc_all_wk12
```

### 26-week model

Set up
```{r}
roc_data26 <- preds26 %>%
  roc_curve(prob_raw, truth = label)

# rocs per fold
roc_folds26 <- preds26 %>%
  nest(.by = outer_split_num, .key = "preds") |> 
  mutate(roc = map(preds, \(preds) roc_curve(preds, prob_raw, 
                                             truth = label)))

fig_roc_folds26 <- roc_data26 %>%  # plot region from full concatenated data 
  ggplot(aes(x = 1 - specificity, y = sensitivity)) + 
  geom_abline(lty = 3) +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(x = "False Positive Rate",
       y = "True Positive Rate") +
  scale_x_continuous(breaks = seq(0,1,.25),
                     labels = sprintf("%.2f", seq(1,0,-.25))) +
  theme(axis.text = element_text(size = rel(0.75)),
        axis.title = element_text(size = rel(1)))

for (i in 1:nrow(roc_folds26)) {
  fig_roc_folds26 <- fig_roc_folds26 +
    geom_path(data = roc_folds26$roc[[i]],
              mapping = aes(x = 1 - specificity, y = sensitivity),
              color = "gray")
}
```

```{r}
#| label: fig-roc-wk26

#add full concatenated curve
fig_roc_all_wk26 <- fig_roc_folds26 +
  geom_path(data = roc_data26,
            mapping = aes(x = 1 - specificity, y = sensitivity, color = "red"),
            linewidth = 2) +
  labs(x = "False Positive Rate",
       title = "Week 26 ROC Curves") +
  theme(legend.position = "none")

fig_roc_all_wk26
```

## Make paneled figure

```{r}
#| label: fig-roc-all
#| fig-cap: "ROC Curves. Dotted, diagonal line represents chance performance (0.5). Grey lines display individual ROC curves from each of 30 held-out folds. Thick, red line displays ROC curve concatenated across all 30 held-out folds. A) 4-week model. B) 12-week model. C) 26-week model."
#| fig-height: 10

fig_roc_all <- fig_roc_all_wk4 + fig_roc_all_wk12 + fig_roc_all_wk26 + 
  plot_layout(ncol = 1) +
  plot_annotation(tag_levels = "A")

fig_roc_all

```

